[xml]$versionXml = Get-Content c:\Pool\AdIntel\src\MIR.new.properties.xml
$node = $versionXml.project.property | where {$_.name -eq 'assembly.version'}
$iterationNumber = $node.value

Set-Content -Path "c:\Pool\AdIntel\src\_shared\temp.txt" "

using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute(`"Mediaresearch a.s.`")]
[assembly: AssemblyCopyrightAttribute(`"Copyright Mediaresearch a.s.`")]
[assembly: AssemblyVersionAttribute(`"$iterationNumber`")]
[assembly: AssemblyInformationalVersionAttribute(`"$iterationNumber`")]
" –Force

