<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Syncfusion.SfSkinManager.WPF">
        <Version>29.2.10</Version>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Syncfusion.Themes.Windows11Light.WPF">
        <HintPath>..\Syncfusion.Themes.Windows11Light.WPF.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
