<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Syncfusion.SfSkinManager.WPF">
        <HintPath>D:\Pool\MintLight\lib\Syncfusion.SfSkinManager.WPF.dll</HintPath>
      </Reference>
      <Reference Include="Syncfusion.Themes.Office2019Colorful_Kite.WPF">
        <HintPath>..\Syncfusion.Themes.Office2019Colorful_Kite.WPF.dll</HintPath>
      </Reference>
      <Reference Include="Syncfusion.Themes.Windows11MintLight.WPF">
        <HintPath>D:\Pool\MintLight\bin\Release\net6.0-windows\Syncfusion.Themes.Windows11MintLight.WPF.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SyncfusionThemeRegistrator\SyncfusionThemeRegistrator.csproj" />
    </ItemGroup>

</Project>
