SELECT
	[self].[OwnerId],
	[self].[MediumId],
	[self].[ActiveFrom],
	[self].[ActiveTo],
	[self].[Created],
	[self].[CreatedBy],
	[self].[Modified],
	[self].[ModifiedBy],
	[self].[Id],
	[t1].[CRN],
	[t1].[OwnershipId],
	[t1].[Created] as [Created1],
	[t1].[CreatedBy] as [CreatedBy1],
	[t1].[Modified] as [Modified1],
	[t1].[ModifiedBy] as [ModifiedBy1],
	[t1].[CrnTypeId],
	[t1].[ActiveFrom] as [ActiveFrom1],
	[t1].[ActiveTo] as [ActiveTo1],
	[t1].[Name],
	[t1].[Id] as [Id1],
	[t2].[OriginalId],
	[t2].[MediaTypeId],
	[t2].[Created] as [Created2],
	[t2].[CreatedBy] as [CreatedBy2],
	[t2].[Modified] as [Modified2],
	[t2].[ModifiedBy] as [ModifiedBy2],
	[t2].[DataMediaSubject],
	[t2].[TvmCodeAto],
	[t2].[ValidFrom],
	[t2].[ValidTo],
	[t2].[PublisherChangeNote],
	[t2].[Note],
	[t2].[PriceListSource],
	[t2].[PriceList],
	[t2].[OriginalName],
	[t2].[Id] as [Id2],
	[t3].[Login],
	[t3].[UserName],
	[t3].[UserTypeId],
	[t3].[Id] as [Id3],
	[t4].[Login] as [Login1],
	[t4].[UserName] as [UserName1],
	[t4].[UserTypeId] as [UserTypeId1],
	[t4].[Id] as [Id4],
	[version].[Name] as [Name1],
	[version].[PublisherId],
	[version].[MediumId] as [MediumId1],
	[version].[PressPeriodicityId],
	[version].[IsMinorChannel],
	[version].[TvlogShift],
	[version].[FocusId],
	[version].[ActiveFrom] as [ActiveFrom2],
	[version].[ActiveTo] as [ActiveTo2],
	[version].[Created] as [Created3],
	[version].[CreatedBy] as [CreatedBy3],
	[version].[Modified] as [Modified3],
	[version].[ModifiedBy] as [ModifiedBy3],
	[version].[NoAggregationTargetGroupId],
	[version].[PageOfEar],
	[version].[Id] as [Id5],
	[t5].[OriginalId] as [OriginalId1],
	[t5].[Name] as [Name2],
	[t5].[Created] as [Created4],
	[t5].[CreatedBy] as [CreatedBy4],
	[t5].[Modified] as [Modified4],
	[t5].[ModifiedBy] as [ModifiedBy4],
	[t5].[CRN] as [CRN1],
	[t5].[Id] as [Id6]
FROM
	[Media].[SelfPromotionDefinition] [self]
		INNER JOIN [Media].[Owner] [t1] ON [self].[OwnerId] = [t1].[Id]
		INNER JOIN [Media].[Medium] [t2] ON [self].[MediumId] = [t2].[Id]
		INNER JOIN [Security].[User] [t3] ON [self].[CreatedBy] = [t3].[Id]
		LEFT JOIN [Security].[User] [t4] ON [self].[ModifiedBy] = [t4].[Id]
		INNER JOIN [Media].[MediumVersion] [version]
			LEFT JOIN [Media].[Publisher] [t5] ON [version].[PublisherId] = [t5].[Id]
		ON [self].[MediumId] = [version].[MediumId]
ORDER BY
	[version].[ActiveTo] DESC
