using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Mediaresearch.Framework.Utilities")]
// nahrazeno hodnotou v ..\_shared\GlobalAssemblyInfo.cs
// [assembly: AssemblyCompanyAttribute("Mediaresearch a.s.")]
[assembly: AssemblyProductAttribute("Framework")]
// nahrazeno hodnotou v ..\_shared\GlobalAssemblyInfo.cs
// [assembly: AssemblyCopyrightAttribute("Copyright Mediaresearch a.s.")]
// nahrazeno hodnotou v ..\_shared\GlobalAssemblyInfo.cs
// [assembly: AssemblyVersionAttribute("1.0.0.694")]


[assembly: AssemblyVersion("3.0.2.0")]
