<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net9.0;net6.0-windows;net7.0-windows;net8.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <Resource Include="Svgs\signal.svg" />
      <None Remove="icons\ADWdracek32.png" />
      <Resource Include="icons\ADWdracek32.png" />
    </ItemGroup>

</Project>
