<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <UseWpf>true</UseWpf>
        <RootNamespace>SyncfusionThemeRegistrator</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Syncfusion.SfSkinManager.WPF">
            <Version>29.2.10</Version>
        </PackageReference>
    </ItemGroup>

</Project>
